// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7iFs46kFKSh7NJj3cQNpGHobxVjhmgA',
    appId: '1:355057773109:web:9b26730e09fc516c36df7c',
    messagingSenderId: '355057773109',
    projectId: 'flutter-login-12bf5',
    authDomain: 'flutter-login-12bf5.firebaseapp.com',
    storageBucket: 'flutter-login-12bf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-sJ_3qKZ2TdbO1mGR5ZomKX0Eg3H7GI',
    appId: '1:355057773109:android:747dc7e5b1616b1b36df7c',
    messagingSenderId: '355057773109',
    projectId: 'flutter-login-12bf5',
    storageBucket: 'flutter-login-12bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0dkPUdqN_NvcYcrzYR5XM49HNyQe8_k',
    appId: '1:355057773109:ios:6ff119f3322e328236df7c',
    messagingSenderId: '355057773109',
    projectId: 'flutter-login-12bf5',
    storageBucket: 'flutter-login-12bf5.appspot.com',
    iosClientId: '355057773109-245bsm1rv7tup9jhkeiarakb2rj07t73.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0dkPUdqN_NvcYcrzYR5XM49HNyQe8_k',
    appId: '1:355057773109:ios:6e8b7a1501aef1bd36df7c',
    messagingSenderId: '355057773109',
    projectId: 'flutter-login-12bf5',
    storageBucket: 'flutter-login-12bf5.appspot.com',
    iosClientId: '355057773109-d31k2i13nh2mjrisc4k03p5h7q7h6nm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
